version: "3.8"
services:
    api:
        image: alpha/beta
        volumes:
            - .:/app
        depends_on:
            - db_api

    db_api:
        image: mysql:8.0
        environment:
            - MYSQL_ROOT_PASSWORD=api
        volumes:
            - ./docker/dev/testing-db.sql:/docker-entrypoint-initdb.d/testing-db.sql

    dockerize:
        image: jwilder/dockerize
